### ISSUE TITLE
Code snippets in the book do not match code on github

### ISSUE THREAD

**Issue by jordanfloyd** [DiscoverMeteor/book#150]
There are several portions throughout the book where the code snippets in the text are wrong. The chapter on editing posts is one place and the chapter on comments is another. I finished the chapters only to have to go back and troubleshoot my code vs what is in github for that chapter. I would suggest going through all the code snippets again and making sure what is printed is actually what is in the commit for that chapter.

**Comment by craigmaslowski** [comment]
I'm going through the whole tutorial again, after the Iron Router update, and have found several problems as well. 

Here's a few of them.

Page 58 (pdf) - First sentence could be confusing. **"So far, we've built our layout using hard-coded template includes (such as {{>header}}."** Change {{>header}} to {{>postList}} as a header template hasn't been created yet at that point in the book. Also missing a closing paren there.

Page 126 (pdf) - code is incorrect since we're no longer updating main.html. code snippet should reflect the correct changes to layout.html

**Comment by tmeasday** [comment]
Thanks a lot for your help guys. I think I've resolved the issues you've posted. A new PDF should appear soon.

**Comment by craigmaslowski** [comment]
Found another one on page 137 in regards to the changes to router.js

```
'clearErrors': function(page) { 
  Errors.clearSeen();
  return page;
}
```

Should be:

```
Router.before(function() { Errors.clearSeen() });
```
