### ISSUE TITLE
Should you tell readers about jQuery.serializeArray

### ISSUE THREAD

**Issue by mitar** [DiscoverMeteor/book#185]
I am not sure about this one, but in the new post form you are using some complicated repetitive jQuery to extract form values into a post document. I am not sure if it would be really better, but maybe at least tell readers about [jQuery.serializeArray](http://api.jquery.com/serializeArray/). It does not get you to the document, but:

```
var post = $.extend.apply(null, $(e.target).serializeArray());
```

Of course it is a bit of jQuery and JavaScript magic, so maybe it is not the best for introductory material. ;-)

**Comment by nylen** [comment]
I agree.  However, your solution does not work for me (it produces `{name: "message", value: "the message text"}` because each `name` and `value` pair overwrite the data from the previous form element).  I suggest the following instead:

```
var data = $(e.target).serializeArray(),
    post = _.object(_.pluck(data, 'name'), _.pluck(data, 'value'));
```

The keys for the new post should be whitelisted to `url`, `title`, and `message`, which is done in the `post` method created later on.

**Comment by mitar** [comment]
Oh, you are completely right. I forgot about this name/value structure. :-(

**Comment by tmeasday** [comment]
It's a tradeoff between helping people do it in the best way and making it simple enough that people won't get distracted by the libraries we use. 

We've avoided using jQuery functionality so far and just stuck to underscore in these scenarios. I think it's OK.
