### ISSUE TITLE
Issue with Route '/' in Voting Chapter Under Ranking the Front Page Posts Section

### ISSUE THREAD

**Issue by ghost** [DiscoverMeteor/book#375]
Under "Ranking the Front Page Posts" section on Voting chapter, looking at the code block for "lib/router.js", I think the path needs to be '/:postsLimit?' instead of '/', the load more doesn't work on the homepage without '/:postsLimit?'. In this case, then I've put the home router below newPosts and bestPosts, because it seemed like home router interfered with those routers if put on top.

Also, please note that the "New" tab is highlighted when the homepage is opened, this is odd.

**Comment by SachaG** [comment]
I'm not sure if I follow entirely, but the "load more" link should point to `/new/10`, not `/10`. Which is why it should work even if we don't have a `/:postsLimit?` path. Does that answer your question?

And the homepage _is_ the New tab. Although in my case the tab isn't highlighted as far as I can tell.

**Comment by ghost** [comment]
Yup that clarifies the book's intentions. Thanks!
