### ISSUE TITLE
Chapter 17 does not seem to be up to date with the Intercom interface.

### ISSUE THREAD

**Issue by davidystephenson** [DiscoverMeteor/book#422]
The behaviors described in the instructions do not occur. For example, there is no "Get Started with Intercom" button, and beginning the sign-up process does not lead to the correct block of code.

**Comment by kaspot** [comment]
there is also another small issue: you wont find the secret key as described in the "Settings for app name" - "Secret Mode" section anymore. You'll have to look for it within "Integrations for app name" - "Secure Mode" section.

**Comment by kaspot** [comment]
Chapter 17 - code snippet for client/main.js after the following paragraph: "Finally, we send it up to Intercom along with each user's _id (since that's what the hash is based on):" has wrong code marked - it should be those two lines that were added:
user_id: Meteor.user()._id,
user_hash: Meteor.user().intercomHash,

**Comment by SachaG** [comment]
Thanks!
