### ISSUE TITLE
How to use github for microscope

### ISSUE THREAD

**Issue by moses5407** [DiscoverMeteor/book#93]
Well, maybe it's just me .. but as a never-used-github-before noob I find it completely unintelligible.

Since it's the chosen method for downloading updates in Discover Meteor, it would be realllly helpful to have some instructions, blow by blow, beyond the link to View on Github.

I did manage to rummage around and download a commit, which I unzipped in my microscope folder after the initial install via meteorite. But, when launching with meteor run the app failed immediately with an error code 1 .. this is on Ubuntu 13.10.

Prior to the commit download and unzip the app ran fine.

So, I'm still doing something wrong .. and about to tear my hair out over the wasted time.

Could you provide a step by step "here's how to find, download and use a commit from our "View on Github" link??? Sooon?? :-)

thanks ... I need to read thru the completed code.

Also, is the Telescope code available somewhere? The book intro says something like building microscope will make the Telescope easier to understand. Presumable this means it is viewable somehow? I'm interested in the karma aspect

Thanks, the book is fantastic .. but the lack of gitgub instructions is frustrating.

**Comment by tmeasday** [comment]
Hey there,

Sorry if you are getting frustrated with git, it can be a steep learning curve.

We wrote the book with an expectation that users would have some understanding of git and javascript as they are pretty universal these days, but I think there's a good argument to have a supplementary chapter on each to at least give those who haven't used them before a chance.

Anyway in the meantime, github has some pretty good resources here: http://training.github.com/

In order to "find, download and use" a commit, you do something like:
1. `git clone https://github.com/DiscoverMeteor/Microscope.git`
2. `cd Microscope`
3. `git checkout TAGNAME` [e.g. `git checkout chapter7-1`]
4. `mrt`

You only really need to do steps 1+2 once.

On the second question, Telescope is here: http://telesc.pe

**Comment by moses5407** [comment]
Thanks for the fast response! I'll give this a try!!

**Comment by moses5407** [comment]
Fantastic! Worked like a charm..thanks!

i'd just point out for those as clueless as I that the "https" path in step
1 is found over on the right of the main github listing for the repository
under https clone url.

see this image:

Also, the way to the chapter tag is via the "releases" link along the top
of the table.

Finally, be SURE to use "mrt" versus "meteor" on the first launch.

thanks again!
Jim
